[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core<2,>=1",
]

[tool.poetry]
name = "tap-betterstack"
version = "0.0.1"
description = "`tap-betterstack` is a Singer tap for Better Stack, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
  "ELT",
  "singer.io",
  "Better Stack",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-betterstack"
repository = "https://github.com/edgarrmondragon/tap-betterstack"
documentation = "https://github.com/edgarrmondragon/tap-betterstack#readme"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "0.28.0"

[tool.poetry.group.dev.dependencies]
singer-sdk = {version = "*", extras = ["testing"]}

[tool.poetry.scripts]
# CLI declaration
"tap-betterstack" = "tap_betterstack.tap:TapBetterStack.cli"

[tool.ruff]
ignore = [
  "ANN101",  # missing-type-self
  "DJ",      # flake8-django
  "FIX002",  # line-contains-todo
]
line-length = 88
select = ["ALL"]
src = ["tap_betterstack", "tests"]
target-version = "py37"
unfixable = [
  "ERA001",  # commented-out-code
]

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201",  # missing-return-type-public-function
  "S101",    # assert
  "SLF001",  # private-member-access
]

[tool.ruff.isort]
known-first-party = ["tap_betterstack"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]
