name: Test tap-betterstack

on:
  push:
    branches: [main]
    paths:
    - tap_betterstack/**
    - tests/**
    - noxfile.py
    - poetry.lock
    - pyproject.toml
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - tap_betterstack/**
    - tests/**
    - noxfile.py
    - poetry.lock
    - pyproject.toml
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      NOXPYTHON: ${{ matrix.python-version }}
      NOXSESSION: tests
      PIP_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Upgrade pip
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version
        poetry self show plugins

    - name: Install Nox
      run: |
        pipx install nox
        pipx inject nox nox-poetry
        nox --version

    - name: Run tests
      env:
        TAP_BETTERSTACK_TOKEN: ${{ secrets.TAP_BETTERSTACK_TOKEN }}
        TAP_BETTERSTACK_START_DATE: ${{ secrets.TAP_BETTERSTACK_START_DATE }}
      run: |
        nox --verbose
